/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaProject;
import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;

/**
 *
 * @author Asus
 */


//------ Language selection class
//------------------------------------------------------------------------------------------------------------------------//

public class selectLang extends javax.swing.JFrame {

    /**
     * Creates new form selectLang
     */
    
    //Constructor
    
    public selectLang() {
        
        //Creates components of GUI for selection
        initComponents();
       
        //Creates greeting according to time of day display
        time();
        
        //Creates date and time
        dateAndTime();
    }
    
    

    
        //Date and time fuction
    
    public void dateAndTime(){
         SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd HH:mm");
         Date date = new Date();
         jLabel5.setText(sdf.format(date)); 
        
    }
    
       //Greeting according to time of day display fuction
    
public void time(){
Calendar c = Calendar.getInstance();

//Get hour of day and compare against greeting options 
//to find correct greeting to display

int timeOfDay = c.get(Calendar.HOUR_OF_DAY);

if(timeOfDay >= 0 && timeOfDay < 12){
    jLabel4.setText("Good morning, bonjour.");        
}else if(timeOfDay >= 12 && timeOfDay < 16){
    jLabel4.setText("Good afternoon, bonne après-midi.");    
}else if(timeOfDay >= 16 && timeOfDay < 21){
   jLabel4.setText("Good evening, bonsoir.");    
}else if(timeOfDay >= 21 && timeOfDay < 24){
   jLabel4.setText("Good night, bonne nuit.");    
}
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //All Components in language GUI
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(439, 300));
        setPreferredSize(new java.awt.Dimension(439, 300));
        setSize(new java.awt.Dimension(200, 200));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Which language do you prefer?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 60, 293, 54);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("English");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setMaximumSize(new java.awt.Dimension(350, 250));
        jButton1.setMinimumSize(new java.awt.Dimension(350, 250));
        jButton1.setPreferredSize(new java.awt.Dimension(330, 250));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 130, 114, 52);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("French");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 130, 121, 52);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText(" Quelle langue préférez-vous?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 100, 290, 16);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Greetings!");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 30, 360, 60);

        jLabel5.setText("Date");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 180, 150, 40);

        jLabel6.setText("Date and Time:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 190, 89, 16);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Downloads\\My Post (2).png")); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-20, -100, 550, 420);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 440, 300);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Button for english
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          
        try{
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 //Creates object of next page after selecting language is a success
                new loginCheck(new Locale("en", "US")).setVisible(true);
            }
        });
        } catch(Exception e){
           
            JOptionPane.showMessageDialog(rootPane, "Error:" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    //Button for french
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        try{
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //Creates object of next page after selecting language is a success
                new loginCheck(new Locale("fr", "FR")).setVisible(true);
            }
        });
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error:" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //Main class of project 
    
    public static void main(String args[]) {
        
        ResourceBundle res = ResourceBundle.getBundle("javaProject.Bundle");
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selectLang().setVisible(true);
            }
        });
   
     }
    
    //Components of GUI declaration
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
}
